development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_db_development
  pool: 5
  username: mark
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_db_test
  pool: 5
  username: mark
  password:

